Bump org.robolectric:robolectric from 4.12 to 4.12.1 (#944)
Bumps
[org.robolectric:robolectric](https://github.com/robolectric/robolectric)
from 4.12 to 4.12.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/robolectric/robolectric/releases">org.robolectric:robolectric's
releases</a>.</em></p>
<blockquote>
<p>Robolectric 4.12.1 is a minor release that addressed two issues:</p>
<ol>
<li>Fixed a NoClassDefFoundError when invoking ShadowLog APIs outside of
a Robolectric environment. See <a
href="https://redirect.github.com/robolectric/robolectric/issues/8957">robolectric/robolectric#8957</a>
for details.</li>
<li>Reduced the amount of spurious log noise that may be generated when
attempting to delete temp directories in Windows. See <a
href="https://redirect.github.com/android/nowinandroid/issues/1242">android/nowinandroid#1242</a>
for details.</li>
</ol>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/robolectric/robolectric/compare/robolectric-4.12...robolectric-4.12.1">https://github.com/robolectric/robolectric/compare/robolectric-4.12...robolectric-4.12.1</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/robolectric/robolectric/commit/46ea4217bd4b7c743a4fc4a489c9003773ed1918"><code>46ea421</code></a>
Bump version to 4.12.1</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/8e9ec0e39c00fb79a6bb467e9542946dbe00c2e2"><code>8e9ec0e</code></a>
Stop logging TempDirectory IOExceptions in Windows</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/85f9641622a7b787c2df750495f03345e0158f2c"><code>85f9641</code></a>
Reduce references to <code>android.util.Log$TerribleFailure</code> in
ShadowLog</li>
<li>See full diff in <a
href="https://github.com/robolectric/robolectric/compare/robolectric-4.12...robolectric-4.12.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.robolectric:robolectric&package-manager=gradle&previous-version=4.12&new-version=4.12.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>