Bump org.robolectric:robolectric from 4.10.3 to 4.11.1 (#521)
Bumps
[org.robolectric:robolectric](https://github.com/robolectric/robolectric)
from 4.10.3 to 4.11.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/robolectric/robolectric/releases">org.robolectric:robolectric's
releases</a>.</em></p>
<blockquote>
<p>Robolectric 4.11.1 is a minor release that addressed three
issues:</p>
<ol>
<li>Fixed a NoClassDefFoundError when using PixelCopy with
compileSdkVersion &lt; 34. See <a
href="https://redirect.github.com/robolectric/robolectric/issues/8577">robolectric/robolectric#8577</a>
for details.</li>
<li>Fixed <code>LocaleManager.setApplicationLocales(LocaleList
locales)</code> in Android U. See <a
href="https://redirect.github.com/robolectric/robolectric/issues/8580">robolectric/robolectric#8580</a>
for details.</li>
<li>Fixed AttributeSetBuilder when referencing sparse resource table
entries by name. See <a
href="https://redirect.github.com/robolectric/robolectric/issues/8578">robolectric/robolectric#8578</a>
for details.</li>
</ol>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/robolectric/robolectric/compare/robolectric-4.11...robolectric-4.11.1">https://github.com/robolectric/robolectric/compare/robolectric-4.11...robolectric-4.11.1</a></p>
<p>Robolectric 4.11 adds support for Android SDK 34 (U). It also
contains many bug fixes, performance improvements, and Shadow API
enhancements. Robolectric 4.11 removes support for Android SDKs 18 and
below. If you need to continue testing on Android SDK levels 18 and
below, continue to use Robolectric 4.10.3.</p>
<p>Note that running tests on SDK 34 requires JDK 17.</p>
<h2>What's Changed</h2>
<ul>
<li>Future proof
ShadowViewGroupTest#hasFocus_shouldReturnTrueIfAnyChildHasFocus. <a
href="https://redirect.github.com/robolectric/robolectric/pull/8034">robolectric/robolectric#8034</a></li>
<li>Future proof ShadowCompanionDeviceManager for AssociationInfo
change. <a
href="https://redirect.github.com/robolectric/robolectric/pull/8035">robolectric/robolectric#8035</a></li>
<li>Let example in README.md to use 4.10-alpha-1 by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8056">robolectric/robolectric#8056</a></li>
<li>Fix some Java Lint naming errors by <a
href="https://github.com/hoisie"><code>@​hoisie</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8058">robolectric/robolectric#8058</a></li>
<li>Prep for OpenGL Matrix impl change in SDKs &gt; T. <a
href="https://redirect.github.com/robolectric/robolectric/pull/8060">robolectric/robolectric#8060</a></li>
<li>Make ShadowJobScheduler thread safe <a
href="https://redirect.github.com/robolectric/robolectric/pull/8064">robolectric/robolectric#8064</a></li>
<li>Update issue templates by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8067">robolectric/robolectric#8067</a></li>
<li>Don't run some gradle tasks when md file changes only by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8068">robolectric/robolectric#8068</a></li>
<li>Remove unused Exception from AndroidTesetEnvironmentTest's method
signature by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8069">robolectric/robolectric#8069</a></li>
<li>Bump com.diffplug.spotless:spotless-plugin-gradle from 6.16.0 to
6.17.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8074">robolectric/robolectric#8074</a></li>
<li>Bump com.googlecode.libphonenumber:libphonenumber from 8.13.7 to
8.13.8 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8075">robolectric/robolectric#8075</a></li>
<li>Import Robolectric Native Graphics tests by <a
href="https://github.com/hoisie"><code>@​hoisie</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/7997">robolectric/robolectric#7997</a></li>
<li>Remove SDK 33 Emulator tests by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8077">robolectric/robolectric#8077</a></li>
<li>Add tests for RNG in GitHub actions by <a
href="https://github.com/hoisie"><code>@​hoisie</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8080">robolectric/robolectric#8080</a></li>
<li>Create separate sandboxes for different graphics modes <a
href="https://redirect.github.com/robolectric/robolectric/pull/8082">robolectric/robolectric#8082</a></li>
<li>Fix issue where <code>Activity#isChangingConfigurations</code> is
incorrectly false during <code>ActivityScenario#recreate</code> in Robo
tests. <a
href="https://redirect.github.com/robolectric/robolectric/pull/8087">robolectric/robolectric#8087</a></li>
<li>Bump asmVersion from 9.4 to 9.5 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8088">robolectric/robolectric#8088</a></li>
<li>Bump androidx.test.ext:junit from 1.1.4 to 1.1.5 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8089">robolectric/robolectric#8089</a></li>
<li>Bump com.google.auto:auto-common from 1.1.2 to 1.2.1 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8090">robolectric/robolectric#8090</a></li>
<li>Bump org.conscrypt:conscrypt-openjdk-uber from 2.4.0 to 2.5.2 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8099">robolectric/robolectric#8099</a></li>
<li>Bump com.googlecode.libphonenumber:libphonenumber from 8.13.8 to
8.13.9 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8100">robolectric/robolectric#8100</a></li>
<li>Bump org.ow2.asm:asm-tree from 9.4 to 9.5 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8102">robolectric/robolectric#8102</a></li>
<li>Add shadow getter/setter method for softApConfiguration. <a
href="https://redirect.github.com/robolectric/robolectric/pull/8107">robolectric/robolectric#8107</a></li>
<li>Add support for ARSC resource table compact encoding <a
href="https://redirect.github.com/robolectric/robolectric/pull/8108">robolectric/robolectric#8108</a></li>
<li>Fix gradle wranings for Kotlin configuration by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8109">robolectric/robolectric#8109</a></li>
<li>Fix comment for maven-dependency-resolver module by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8111">robolectric/robolectric#8111</a></li>
<li>Remove mockito-core from utils' test dependencies list by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8112">robolectric/robolectric#8112</a></li>
<li>Remove duplicated gradle plugin maven repository by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8113">robolectric/robolectric#8113</a></li>
<li>Fix AssetManagerTest on android U <a
href="https://redirect.github.com/robolectric/robolectric/pull/8117">robolectric/robolectric#8117</a></li>
<li>Migrate some Gradle's task definations to task.register by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8114">robolectric/robolectric#8114</a></li>
<li>Support partial AppComponentFactory in Robolectric by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8004">robolectric/robolectric#8004</a></li>
<li>Remove executable flag for some Java files by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8121">robolectric/robolectric#8121</a></li>
<li>Fix doc typo for ShadowWebview by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8123">robolectric/robolectric#8123</a></li>
<li>Update requestDismissKeyguard to turn screen on. <a
href="https://redirect.github.com/robolectric/robolectric/pull/8125">robolectric/robolectric#8125</a></li>
<li>Bump com.diffplug.spotless:spotless-plugin-gradle from 6.17.0 to
6.18.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8127">robolectric/robolectric#8127</a></li>
<li>Add test for ParameterizedRobolectricTestRunner with Kotlin by <a
href="https://github.com/utzcoz"><code>@​utzcoz</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8122">robolectric/robolectric#8122</a></li>
<li>Bump androidx.core:core from 1.9.0 to 1.10.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/robolectric/robolectric/pull/8126">robolectric/robolectric#8126</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/robolectric/robolectric/commit/31bccea5fa3b8d2e8bbf0addd17a468e28d84d63"><code>31bccea</code></a>
Bump version to 4.11.1.</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/d15ace8b6c4199ce54e874bafec6e45917ec38f2"><code>d15ace8</code></a>
Fix AttributeSetBuilder lookups with sparse resource table encoding</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/062066cb6775ebc731bd59092d746c3ae218fbab"><code>062066c</code></a>
Fix LocaleManager.setApplicationLocales(LocaleList) in Android U+</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/b35b0bf4e8692296ed924e76ac31945852179cae"><code>b35b0bf</code></a>
Fix ShadowPixelCopy for projects with compileSdk &lt; 34</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/ef09063317b9d0163c712212d5f6ec92e676b22e"><code>ef09063</code></a>
Bump version to 4.11.</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/a29c7a6d4005354ec63691f158d66fe6b8a0d37f"><code>a29c7a6</code></a>
Fix zero-width text views for LEGACY graphics in Android U+</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/d0686422826a376e192b6c85f464307c29b04349"><code>d068642</code></a>
Add support for 2-arg Typeface constructor in legacy ShadowTypeface</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/1341c5718611f6d8707baa10193694a138065e95"><code>1341c57</code></a>
Merge branch 'master' into robolectric-4.11.x</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/d75572bace2be86d3b3db9d0992e28d6bbd88589"><code>d75572b</code></a>
Downgrade guava to 31.1 and stop auto updates.</li>
<li><a
href="https://github.com/robolectric/robolectric/commit/8ce173244ef572c2ec0f65f7cf091e585686c266"><code>8ce1732</code></a>
Merge branch 'master' into robolectric-4.11.x</li>
<li>Additional commits viewable in <a
href="https://github.com/robolectric/robolectric/compare/robolectric-4.10.3...robolectric-4.11.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.robolectric:robolectric&package-manager=gradle&previous-version=4.10.3&new-version=4.11.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Tim Froehlich <froeht@google.com>