Bump androidx.media3:media3-exoplayer from 1.3.0 to 1.3.1 (#994)
Bumps
[androidx.media3:media3-exoplayer](https://github.com/androidx/media)
from 1.3.0 to 1.3.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/androidx/media/releases">androidx.media3:media3-exoplayer's
releases</a>.</em></p>
<blockquote>
<h2>1.3.1</h2>
<p>This release includes the following changes since the 1.3.0
release:</p>
<ul>
<li>Common Library:
<ul>
<li>Add <code>Format.labels</code> to allow localized or other
alternative labels.</li>
</ul>
</li>
<li>ExoPlayer:
<ul>
<li>Fix issue where <code>PreloadMediaPeriod</code> cannot retain the
streams when it is preloaded again.</li>
<li>Apply the correct corresponding <code>TrackSelectionResult</code> to
the playing period in track reselection.</li>
<li>Start early-enabled renderers only after advancing the playing
period when transitioning between media items (<a
href="https://redirect.github.com/androidx/media/issues/1017">#1017</a>).</li>
<li>Add missing return type to proguard
<code>-keepclasseswithmembers</code> rule for
<code>DefaultVideoFrameProcessor.Factory.Builder.build()</code> (<a
href="https://redirect.github.com/androidx/media/issues/1187">#1187</a>).</li>
</ul>
</li>
<li>Transformer:
<ul>
<li>Add workaround for exception thrown due to <code>MediaMuxer</code>
not supporting negative presentation timestamps before API 30.</li>
</ul>
</li>
<li>Track Selection:
<ul>
<li><code>DefaultTrackSelector</code>: Prefer video tracks with a
'reasonable' frame rate (&gt;=10fps) over those with a lower or unset
frame rate. This ensures the player selects the 'real' video track in
MP4s extracted from motion photos that can contain two HEVC tracks where
one has a higher resolution but a very small number of frames (<a
href="https://redirect.github.com/androidx/media/issues/1051">#1051</a>).</li>
</ul>
</li>
<li>Extractors:
<ul>
<li>Fix issue where padding was not skipped when reading odd-sized
chunks from WAV files (<a
href="https://redirect.github.com/androidx/media/pull/1117">#1117</a>).</li>
<li>MP3: Populate <code>Format.averageBitrate</code> from metadata
frames such as <code>XING</code> and <code>VBRI</code>.</li>
<li>MPEG-TS: Revert a change that aimed to ensure the last frame is
rendered by passing the last access unit of a stream to the sample queue
(<a
href="https://redirect.github.com/google/ExoPlayer/issues/7909">#7909</a>).
This is due to the change causing new problems with I-frame only HLS
streams (<a
href="https://redirect.github.com/google/ExoPlayer/issues/1150">#1150</a>)
and H.262 HLS streams (<a
href="https://redirect.github.com/google/ExoPlayer/issues/1126">#1126</a>).</li>
</ul>
</li>
<li>Audio:
<ul>
<li>Allow renderer recovery by disabling offload if audio track fails to
initialize in offload mode.</li>
</ul>
</li>
<li>Video:
<ul>
<li>Add workaround for a device issue on Galaxy Tab S7 FE, Chromecast
with Google TV, and Lenovo M10 FHD Plus that causes 60fps H265 streams
to be marked as unsupported</li>
<li>Add workaround that ensures the first frame is always rendered while
tunneling even if the device does not do this automatically as required
by the API (<a
href="https://redirect.github.com/androidx/media/issues/1169">#1169</a>).
(<a
href="https://redirect.github.com/androidx/media/issues/966">#966</a>).</li>
<li>Fix issue where HDR color info handling causes codec misbehavior and
prevents adaptive format switches for SDR video tracks (<a
href="https://redirect.github.com/androidx/media/issues/1158">#1158</a>).</li>
</ul>
</li>
<li>Text:
<ul>
<li>WebVTT: Prevent directly consecutive cues from creating spurious
additional <code>CuesWithTiming</code> instances from
<code>WebvttParser.parse</code> (<a
href="https://redirect.github.com/androidx/media/issues/1177">#1177</a>).</li>
</ul>
</li>
<li>DRM:
<ul>
<li>Work around a <code>NoSuchMethodError</code> which can be thrown by
the <code>MediaDrm</code> framework instead of
<code>ResourceBusyException</code> or
<code>NotProvisionedException</code> on some Android 14 devices (<a
href="https://redirect.github.com/androidx/media/issues/1145">#1145</a>).</li>
</ul>
</li>
<li>Effect:
<ul>
<li>Improved PQ to SDR tone-mapping by converting color spaces.</li>
</ul>
</li>
<li>Session:
<ul>
<li>Fix issue where the current position jumps back when the controller
replaces the current item (<a
href="https://redirect.github.com/androidx/media/issues/951">#951</a>).</li>
<li>Fix issue where <code>MediaMetadata</code> with just non-null
<code>extras</code> is not transmitted between media controllers and
sessions (<a
href="https://redirect.github.com/androidx/media/issues/1176">#1176</a>).</li>
</ul>
</li>
<li>UI:
<ul>
<li>Fallback to include audio track language name if <code>Locale</code>
cannot identify a display name (<a
href="https://redirect.github.com/androidx/media/issues/988">#988</a>).</li>
</ul>
</li>
<li>DASH Extension:
<ul>
<li>Populate all <code>Label</code> elements from the manifest into
<code>Format.labels</code> (<a
href="https://redirect.github.com/androidx/media/pull/1054">#1054</a>).</li>
</ul>
</li>
<li>RTSP Extension:
<ul>
<li>Skip empty session information values (i-tags) in SDP parsing (<a
href="https://redirect.github.com/androidx/media/issues/1087">#1087</a>).</li>
</ul>
</li>
<li>Decoder Extensions (FFmpeg, VP9, AV1, MIDI, etc.):
<ul>
<li>Disable the MIDI extension as a local dependency by default because
it requires an additional Maven repository to be configured. Users who
need this module from a local dependency <a
href="https://github.com/androidx/media/blob/main/README.md#midi-module">can
re-enable it</a>.</li>
</ul>
</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/androidx/media/blob/release/RELEASENOTES.md">androidx.media3:media3-exoplayer's
changelog</a>.</em></p>
<blockquote>
<h3>1.3.1 (2024-04-11)</h3>
<p>This release includes the following changes since the
<a
href="https://github.com/androidx/media/blob/release/#130-2024-03-06">1.3.0
release</a>:</p>
<ul>
<li>Common Library:
<ul>
<li>Add <code>Format.labels</code> to allow localized or other
alternative labels.</li>
</ul>
</li>
<li>ExoPlayer:
<ul>
<li>Fix issue where <code>PreloadMediaPeriod</code> cannot retain the
streams when it
is preloaded again.</li>
<li>Apply the correct corresponding <code>TrackSelectionResult</code> to
the playing
period in track reselection.</li>
<li>Start early-enabled renderers only after advancing the playing
period
when transitioning between media items
(<a
href="https://redirect.github.com/androidx/media/issues/1017">#1017</a>).</li>
<li>Add missing return type to proguard
<code>-keepclasseswithmembers</code> rule for
<code>DefaultVideoFrameProcessor.Factory.Builder.build()</code>
(<a
href="https://redirect.github.com/androidx/media/issues/1187">#1187</a>).</li>
</ul>
</li>
<li>Transformer:
<ul>
<li>Add workaround for exception thrown due to <code>MediaMuxer</code>
not supporting
negative presentation timestamps before API 30.</li>
</ul>
</li>
<li>Track Selection:
<ul>
<li><code>DefaultTrackSelector</code>: Prefer video tracks with a
'reasonable' frame
rate (&gt;=10fps) over those with a lower or unset frame rate. This
ensures
the player selects the 'real' video track in MP4s extracted from motion
photos that can contain two HEVC tracks where one has a higher
resolution but a very small number of frames
(<a
href="https://redirect.github.com/androidx/media/issues/1051">#1051</a>).</li>
</ul>
</li>
<li>Extractors:
<ul>
<li>Fix issue where padding was not skipped when reading odd-sized
chunks
from WAV files (<a
href="https://redirect.github.com/androidx/media/pull/1117">#1117</a>).</li>
<li>MP3: Populate <code>Format.averageBitrate</code> from metadata
frames such as
<code>XING</code> and <code>VBRI</code>.</li>
<li>MPEG-TS: Revert a change that aimed to ensure the last frame is
rendered
by passing the last access unit of a stream to the sample queue
(<a
href="https://redirect.github.com/google/ExoPlayer/issues/7909">#7909</a>).
This is due
to the change causing new problems with I-frame only HLS streams
(<a
href="https://redirect.github.com/google/ExoPlayer/issues/1150">#1150</a>)
and H.262 HLS
streams (<a
href="https://redirect.github.com/google/ExoPlayer/issues/1126">#1126</a>).</li>
</ul>
</li>
<li>Audio:
<ul>
<li>Allow renderer recovery by disabling offload if audio track fails to
initialize in offload mode.</li>
</ul>
</li>
<li>Video:
<ul>
<li>Add workaround for a device issue on Galaxy Tab S7 FE, Chromecast
with
Google TV, and Lenovo M10 FHD Plus that causes 60fps H265 streams to be
marked as unsupported</li>
<li>Add workaround that ensures the first frame is always rendered while
tunneling even if the device does not do this automatically as required
by the API (<a
href="https://redirect.github.com/androidx/media/issues/1169">#1169</a>).
(<a
href="https://redirect.github.com/androidx/media/issues/966">#966</a>).</li>
</ul>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/androidx/media/commit/d833d59124d795afc146322fe488b2c0d4b9af6a"><code>d833d59</code></a>
Update Media3 version number</li>
<li><a
href="https://github.com/androidx/media/commit/1792723be29c4735194b9342f59efd636bcd22b9"><code>1792723</code></a>
Update release notes for 1.3.1 bug fix release</li>
<li><a
href="https://github.com/androidx/media/commit/1a710b06d02545e5a166c2ad2c5620ef49a255be"><code>1a710b0</code></a>
Import string translations</li>
<li><a
href="https://github.com/androidx/media/commit/5fe906f1e95e572272c883bbeb7e9561a0a8d6b5"><code>5fe906f</code></a>
Rollback of <a
href="https://github.com/androidx/media/commit/e665e2aee8f4cb0ad702a102">https://github.com/androidx/media/commit/e665e2aee8f4cb0ad702a102</a>...</li>
<li><a
href="https://github.com/androidx/media/commit/7b5522fc589b2e11a362f8ee430e4cd90c0a7947"><code>7b5522f</code></a>
Merge pull request <a
href="https://redirect.github.com/androidx/media/issues/1054">#1054</a>
from jekopena:main</li>
<li><a
href="https://github.com/androidx/media/commit/4caed3cfb2d0500fd5e9c04e47661385847b3fc0"><code>4caed3c</code></a>
Add <code>PlayerView.setControllerAnimationEnabled(boolean)</code></li>
<li><a
href="https://github.com/androidx/media/commit/26ce3f012a0c8c113009b50963016fcc9831f1a7"><code>26ce3f0</code></a>
Fix javadoc on
<code>PlayerView.setControllerVisibilityListener</code></li>
<li><a
href="https://github.com/androidx/media/commit/a5d0cb51bc837d2481aa42e1610cea3524a169bc"><code>a5d0cb5</code></a>
Don't apply performance point workaround from API 35</li>
<li><a
href="https://github.com/androidx/media/commit/88ebc89da2c7ad4da51a5ed7f1f68901defa176b"><code>88ebc89</code></a>
Plumb MP3 average bitrate from metadata frames into Format</li>
<li><a
href="https://github.com/androidx/media/commit/dca3c61c5b733fd2017fab3295870c931f02dc3b"><code>dca3c61</code></a>
In-line versions only used by exoplayer-media2 extension</li>
<li>Additional commits viewable in <a
href="https://github.com/androidx/media/compare/1.3.0...1.3.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=androidx.media3:media3-exoplayer&package-manager=gradle&previous-version=1.3.0&new-version=1.3.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>